---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{name}}
  namespace: {{namespace}}
  labels:
    app: {{name}}
    repo: {{repo}}
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - {{dns_name}}
    secretName: {{name}}-tls
  rules:
  - host: {{dns_name}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{name}}
          servicePort: 80
