---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{onboarding.name}}
  namespace: {{onboarding.namespace}}
  labels:
    app: {{onboarding.name}}
    repo: {{onboarding.repo}}
  # annotations:
  #   certmanager.k8s.io/cluster-issuer: letsencrypt-staging
spec:
  # tls:
  # - hosts:
  #   - {{onboarding.dns_name}}
  #   secretName: {{onboarding.name}}-tls
  rules:
  - host: {{onboarding.dns_name}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{onboarding.name}}
          servicePort: 80
