---
kind: PodDisruptionBudget
apiVersion: policy/v1beta1
metadata:
  name: {{name}}
  namespace: {{namespace}}
  labels:
    app: {{name}}
    repo: {{repo}}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{name}}
      repo: {{repo}}
