---
kind: PodDisruptionBudget
apiVersion: policy/v1beta1
metadata:
  name: {{onboarding.name}}
  namespace: {{onboarding.namespace}}
  labels:
    app: {{onboarding.name}}
    repo: {{onboarding.repo}}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{onboarding.name}}
      repo: {{onboarding.repo}}
