---
version: '3.7'

services:

  x-default: &base
    build:
      context: .
      target: dev
      args:
        - KUBE_VERSION=v1.20.15
        - AWSIAMAUTHENTICATOR_VERSION=v0.5.7
    working_dir: /app
    platform: linux/amd64
    volumes:
      - "$HOME/.aws:/root/.aws"
      - "$HOME/.kube:/root/.kube"
      - /app/node_modules
      - ".:/app"

  sh:
    <<: *base
    entrypoint:
      - "bash"

  test: 
    <<: *base
    entrypoint:
      - yarn
      - run
      - test

  ntpl:
    <<: *base
    build:
      context: .
      target: release
      args:
        - KUBE_VERSION=v1.20.15
        - AWSIAMAUTHENTICATOR_VERSION=v0.5.7
    image: ikerry/ntpl:v2.0.1-k8sv1.20.15
    entrypoint: 
      - "bash"