#!/usr/bin/env node

const ntpl = require('commander'),
    Mustache = require('mustache'),
    utils = require('./utils/utility'),
    parser = require('./utils/parser'),
    shell = require('shelljs'),
    supportList = ['yaml', 'yml'];

let data = {
  component: '',
  list: [],
  params: {}
}

ntpl
  .version('0.3.0', '-v, --version')
  .option('-c, --component <file ...>', 'kubernetes component', componentReader)
  .option('-p, --parameters <file ...>', 'parameters file (yaml|yml)', parameterReader)

ntpl
  .command('compile')
  .description('Compile kubernetes templates.')
  .action(() => {
    kubeCompile()
  })

ntpl
  .command('validate')
  .description('Validate kubernetes templates.')
  .action(() => {
    kubeCompile().then(() => kubeValidate())
  })

ntpl
  .command('apply')
  .description('Apply templates into kubernetes.')
  .action(() => {
    kubeCompile().then(() => kubeApply())
  })

ntpl
  .command('delete')
  .description('Delete templates from kubernetes')
  .action(() => {
    kubeCompile().then(() => kubeDelete())
  })

ntpl
  .parse(process.argv);

function parameterReader(filePath) {
  if (utils.isInSupportList(filePath, supportList)) {
    data.list.push(filePath)
  }
  return data.list
}

function componentReader(component){
  return data.component = component;
}

function kubeCompile() {
  const buildPath = `_build`,
        componentFolderPath = `templates/${data.component}`;

  return parser.parameterBuilder(data.list)
    .then(params => { return data.params = params })
    .then(() => utils.clean(buildPath))
    .then(() => utils.mkdir(`${buildPath}/${data.component}`))
    .then(() => utils.readdir(componentFolderPath))
    .then(files => Promise.all(files.map(file =>
        utils.readfile(`${componentFolderPath}/${file}`)
        .then(content => Mustache.render(content, data.params))
        .then(content => utils.appendFile(`${buildPath}/${data.component}/${file}`, content))
      ))
    )
}

function buildComponentFolderReader(component) {
  const buildFolderPath = `_build/${component}`;
  return utils.readdir(buildFolderPath)
}

function kubeValidate() {
  const buildFolderPath = `_build/${data.component}`;
  return buildComponentFolderReader(data.component)
  .then(files => files.map(file => shell.exec(`kubectl apply --validate --dry-run  -f ${buildFolderPath}/${file}`)))
}

function kubeApply() {
  const buildFolderPath = "_build/" + data.component
  return buildComponentFolderReader(data.component)
  .then(files => files.map(file => shell.exec(`kubectl apply -f ${buildFolderPath}/${file}`)))
}

function kubeDelete() {
  const buildFolderPath = "_build/" + data.component
  return buildComponentFolderReader(data.component)
  .then(files => files.map(file => shell.exec(`kubectl delete -f ${buildFolderPath}/${file}`)))
}
