#!/usr/bin/env node

const ntpl = require('commander'),
    yaml = require('js-yaml'),
    Mustache = require('mustache');
    fs = require('fs');

let data = {
  tpl: ``,
  params: ``
}

ntpl
  .version('0.1.5', '-v, --version')
  .option('-t, --template <file ...>', 'kubernetes template yaml', templateReader)
  .option('-p, --parameters <file ...>', 'parameters yaml', parametersReader)
  .parse(process.argv);

function templateReader(filePath){
  data.tpl = fs.readFileSync(filePath, 'utf8');
}

function parametersReader(filePath) {
  data.params = yaml.load(fs.readFileSync(filePath, 'utf8'));
}

console.log(Mustache.render(data.tpl, data.params))
