---
version: 2.1
jobs:
  ut:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Unit Test
          command: |
            make test

  deploy:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Deploy to Docker Hub
          command: |
            echo ${DOCKER_PASSWORD} | base64 --decode | docker login -u $DOCKER_USER --password-stdin
            make push-${CIRCLE_TAG}

workflows:
  version: 2
  any-commit:
    jobs:
      - ut
  release:
    jobs:
      - deploy:
          context: Docker
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
